services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "StrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P StrongPassword123! -Q 'SELECT 1' -C
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./MarketAssetsAPI
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=MarketAssetsDB;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=True
      - Fintacharts__BaseUrl=https://platform.fintacharts.com
      - Fintacharts__WssUrl=wss://platform.fintacharts.com
      - Fintacharts__Realm=fintatech
      - Fintacharts__ClientId=app-cli
      - Fintacharts__Username=r_test@fintatech.com
      - Fintacharts__Password=kisfiz-vUnvy9-sopnyv
    depends_on:
      db:
        condition: service_healthy

volumes:
  sqldata: